name: Replenishment Pipeline

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '0 0 * * *'  #midnight everyday

jobs:
  replenishment_pipeline_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.14'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Hopsworks API Key
        run: echo "HOPSWORKS_KEY=${{ secrets.HOPSWORKS_KEY }}" >> $GITHUB_ENV

      - name: Execute Replenishment Pipeline Notebook
        env:
          HOPSWORKS_KEY: ${{ secrets.HOPSWORKS_KEY }}
        run: |
          jupyter nbconvert --to notebook --execute notebooks/replenishment_pipeline.ipynb 
